# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            'Chinmay Kulkarni'
tagline:          'Assistant Professor, CMU HCII'
description:      "Chinmay Kulkarni is an Assistant Professor in Carnegie Mellon's HCI Institute. His research studies and builds systems for large-scale learning, work, and mentoring."
url:              http://cs.cmu.edu/~chinmayk
baseurl:          /~chinmayk/
excerpt_separator: <!--more-->

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins: [jekyll-paginate-v2]
